declare module "*.png";
declare module "*.svg";
declare module "*.jpeg";
declare module "*.jpg";
declare module "*.css";
declare module "light-bolt11-decoder";
declare module "react-datepicker";
declare module "react-helmet";
declare module "react-tag-autocomplete";
